"""Generate the exact Chaquopy CPython 3.12 HTML5 entity table used by Android dedup."""

from __future__ import annotations

import hashlib
import html.entities
import json
import platform
import sys
from pathlib import Path, PurePosixPath
from typing import NoReturn, Sequence

from .core import ContractError, _atomic_write, _open_repo, _read_regular_file


KOTLIN_OUTPUT_PATH = PurePosixPath(
    "app/src/main/kotlin/com/ankiminer/android/anki/generated/Html5EntitiesV312.kt"
)
# The device runtime is Chaquopy's 3.12.12-0 target. Its packaged
# ``stdlib-common.imy`` was inspected directly: both this canonical table hash and
# CHARREF_PATTERN match the local CPython 3.12.13 generator interpreter.
TARGET_RUNTIME = "Chaquopy CPython 3.12.12-0"
GENERATOR_PYTHON_VERSION = (3, 12, 13)
TABLE_SHA256 = "0155d7c70a78db0554d8482f86017ad4c2ba9afec237399819d1f560dea33218"
TABLE_ENTRY_COUNT = 2231
CHARREF_PATTERN = r"&(#[0-9]+;?|#[xX][0-9a-fA-F]+;?|[^\t\n\f <&#;]{1,32};?)"
CHARREF_PATTERN_SHA256 = "89b5e85253067a9eb2b748d4906c458114491a06019b2bcc9fb87e40095d0eef"
_MAX_OUTPUT_BYTES = 256 * 1024


def _fail(message: str) -> NoReturn:
    raise ContractError(message)


def _canonical_table(table: dict[str, str]) -> bytes:
    return json.dumps(
        table,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def load_pinned_table() -> tuple[tuple[str, str], ...]:
    if (
        platform.python_implementation() != "CPython"
        or sys.version_info[:3] != GENERATOR_PYTHON_VERSION
    ):
        _fail("HTML5 entity generation requires the pinned CPython 3.12.13 interpreter")
    table = html.entities.html5
    if type(table) is not dict or len(table) != TABLE_ENTRY_COUNT:
        _fail("CPython HTML5 entity table shape drifted")
    raw = _canonical_table(table)
    if hashlib.sha256(raw).hexdigest() != TABLE_SHA256:
        _fail("CPython HTML5 entity table content drifted")
    entries = tuple(sorted(table.items()))
    if any(
        not name
        or len(name) > 32
        or not name.isascii()
        or "\x00" in name
        or not value
        or "\x00" in value
        for name, value in entries
    ):
        _fail("CPython HTML5 entity table contains an unsupported entry")
    return entries


def _kotlin_escape(value: str) -> str:
    result: list[str] = []
    for character in value:
        code_point = ord(character)
        if character == "\\":
            result.append("\\\\")
        elif character == '"':
            result.append('\\"')
        elif character == "$":
            result.append("\\$")
        elif character == "\t":
            result.append("\\t")
        elif character == "\n":
            result.append("\\n")
        elif 0x20 <= code_point <= 0x7E:
            result.append(character)
        elif code_point <= 0xFFFF:
            result.append(f"\\u{code_point:04X}")
        else:
            scalar = code_point - 0x10000
            result.append(f"\\u{0xD800 + (scalar >> 10):04X}")
            result.append(f"\\u{0xDC00 + (scalar & 0x3FF):04X}")
    return "".join(result)


def _render_packed(entries: Sequence[tuple[str, str]], component: int) -> list[str]:
    lines: list[str] = []
    for index, entry in enumerate(entries):
        separator = "\\u0000" if index + 1 < len(entries) else ""
        suffix = " +" if index + 1 < len(entries) else ""
        lines.append(f'        "{_kotlin_escape(entry[component])}{separator}"{suffix}')
    return lines


def generate_kotlin(entries: Sequence[tuple[str, str]]) -> bytes:
    checked = tuple(entries)
    if not checked or tuple(sorted(checked)) != checked:
        _fail("HTML5 entity entries must be non-empty and sorted")
    if len({name for name, _ in checked}) != len(checked):
        _fail("HTML5 entity entries repeat a name")
    lines = [
        "// Generated by tools/anki-contract/generate_html5_entities.py --refresh.",
        "// Runtime source: Chaquopy CPython 3.12.12-0 html.entities.html5.",
        "// Generator: CPython 3.12.13, verified to the same canonical table hash.",
        f"// Canonical table SHA-256: {TABLE_SHA256}",
        "// Do not edit by hand.",
        "",
        "package com.ankiminer.android.anki.generated",
        "",
        "internal object Html5EntitiesV312 {",
        f'    const val SOURCE_SHA256 = "{TABLE_SHA256}"',
        f"    const val ENTRY_COUNT = {len(checked)}",
        "",
        "    private const val PACKED_NAMES =",
    ]
    lines.extend(_render_packed(checked, 0))
    lines.extend(["", "    private const val PACKED_VALUES ="])
    lines.extend(_render_packed(checked, 1))
    lines.extend(
        [
            "",
            "    private val names: List<String> by lazy(LazyThreadSafetyMode.PUBLICATION) {",
            "        PACKED_NAMES.split('\\u0000').also { check(it.size == ENTRY_COUNT) }",
            "    }",
            "    private val values: List<String> by lazy(LazyThreadSafetyMode.PUBLICATION) {",
            "        PACKED_VALUES.split('\\u0000').also { check(it.size == ENTRY_COUNT) }",
            "    }",
            "",
            "    fun lookup(name: String): String? {",
            "        val index = names.binarySearch(name)",
            "        return if (index >= 0) values[index] else null",
            "    }",
            "",
            "    internal fun nameAt(index: Int): String = names[index]",
            "",
            "    internal fun valueAt(index: Int): String = values[index]",
            "}",
            "",
        ]
    )
    rendered = "\n".join(lines).encode("utf-8")
    if len(rendered) > _MAX_OUTPUT_BYTES:
        _fail("generated HTML5 entity table exceeds its size bound")
    return rendered


def refresh(repo_root: Path) -> None:
    rendered = generate_kotlin(load_pinned_table())
    with _open_repo(repo_root) as repo_fd:
        _atomic_write(repo_fd, KOTLIN_OUTPUT_PATH, rendered)


def check(repo_root: Path) -> None:
    expected = generate_kotlin(load_pinned_table())
    with _open_repo(repo_root) as repo_fd:
        actual = _read_regular_file(
            repo_fd,
            KOTLIN_OUTPUT_PATH,
            description="generated Kotlin HTML5 entities",
            max_bytes=_MAX_OUTPUT_BYTES,
        )
    if actual != expected:
        _fail(
            "generated Kotlin HTML5 entities drifted; run "
            "tools/anki-contract/generate_html5_entities.py --refresh"
        )
