# Derived from Yomitan (https://github.com/yomidevs/yomitan),
# ext/js/language/ja/japanese-transforms.js, commit e2ed450c2f11a591922822e77f008e70a87daf0c,
# mechanically materialized (generator helpers pre-expanded, transform
# names and rule argument order preserved verbatim; description strings
# omitted — they are upstream UI text). Regenerate against a newer
# upstream commit by re-running the dump documented in licenses/yomitan/.
#
# Copyright (C) 2024-2026  Yomitan Authors
# Copyright (C) 2026  anki_miner contributors (Python port)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Yomitan Japanese deinflection rule table (data only, no engine import).

54 transforms / 834 materialized rules /
22 condition types, consumed by
``deinflection.Deinflector``. GENERATED FILE — edit upstream and
regenerate rather than hand-editing rules.
"""

from __future__ import annotations

from typing import Any


def suffix_inflection(
    inflected: str,
    deinflected: str,
    conditions_in: list[str],
    conditions_out: list[str],
) -> dict[str, Any]:
    """Rule matching an inflected suffix (upstream ``suffixInflection``)."""
    return {
        "type": "suffix",
        "inflected": inflected,
        "deinflected": deinflected,
        "conditionsIn": conditions_in,
        "conditionsOut": conditions_out,
    }


def whole_word_inflection(
    inflected: str,
    deinflected: str,
    conditions_in: list[str],
    conditions_out: list[str],
) -> dict[str, Any]:
    """Rule matching an entire word (upstream ``wholeWordInflection``)."""
    return {
        "type": "wholeWord",
        "inflected": inflected,
        "deinflected": deinflected,
        "conditionsIn": conditions_in,
        "conditionsOut": conditions_out,
    }


CONDITIONS: dict[str, dict[str, Any]] = {
    "v": {"isDictionaryForm": False, "subConditions": ["v1", "v5", "vk", "vs", "vz"]},
    "v1": {"isDictionaryForm": True, "subConditions": ["v1d", "v1p"]},
    "v1d": {"isDictionaryForm": False},
    "v1p": {"isDictionaryForm": False},
    "v5": {"isDictionaryForm": True, "subConditions": ["v5d", "v5s"]},
    "v5d": {"isDictionaryForm": False},
    "v5s": {"isDictionaryForm": False, "subConditions": ["v5ss", "v5sp"]},
    "v5ss": {"isDictionaryForm": False},
    "v5sp": {"isDictionaryForm": False},
    "vk": {"isDictionaryForm": True},
    "vs": {"isDictionaryForm": True},
    "vz": {"isDictionaryForm": True},
    "adj-i": {"isDictionaryForm": True},
    "-ます": {"isDictionaryForm": False},
    "-ません": {"isDictionaryForm": False},
    "-て": {"isDictionaryForm": False},
    "-ば": {"isDictionaryForm": False},
    "-く": {"isDictionaryForm": False},
    "-た": {"isDictionaryForm": False},
    "-ん": {"isDictionaryForm": False},
    "-なさい": {"isDictionaryForm": False},
    "-ゃ": {"isDictionaryForm": False},
}


TRANSFORMS: list[dict[str, Any]] = [
    {
        "id": "-ば",
        "name": "-ば",
        "rules": [
            suffix_inflection("ければ", "い", ["-ば"], ["adj-i"]),
            suffix_inflection("えば", "う", ["-ば"], ["v5"]),
            suffix_inflection("けば", "く", ["-ば"], ["v5"]),
            suffix_inflection("げば", "ぐ", ["-ば"], ["v5"]),
            suffix_inflection("せば", "す", ["-ば"], ["v5"]),
            suffix_inflection("てば", "つ", ["-ば"], ["v5"]),
            suffix_inflection("ねば", "ぬ", ["-ば"], ["v5"]),
            suffix_inflection("べば", "ぶ", ["-ば"], ["v5"]),
            suffix_inflection("めば", "む", ["-ば"], ["v5"]),
            suffix_inflection("れば", "る", ["-ば"], ["v1", "v5", "vk", "vs", "vz"]),
            suffix_inflection("れば", "", ["-ば"], ["-ます"]),
        ],
    },
    {
        "id": "-ゃ",
        "name": "-ゃ",
        "rules": [
            suffix_inflection("けりゃ", "ければ", ["-ゃ"], ["-ば"]),
            suffix_inflection("きゃ", "ければ", ["-ゃ"], ["-ば"]),
            suffix_inflection("や", "えば", ["-ゃ"], ["-ば"]),
            suffix_inflection("きゃ", "けば", ["-ゃ"], ["-ば"]),
            suffix_inflection("ぎゃ", "げば", ["-ゃ"], ["-ば"]),
            suffix_inflection("しゃ", "せば", ["-ゃ"], ["-ば"]),
            suffix_inflection("ちゃ", "てば", ["-ゃ"], ["-ば"]),
            suffix_inflection("にゃ", "ねば", ["-ゃ"], ["-ば"]),
            suffix_inflection("びゃ", "べば", ["-ゃ"], ["-ば"]),
            suffix_inflection("みゃ", "めば", ["-ゃ"], ["-ば"]),
            suffix_inflection("りゃ", "れば", ["-ゃ"], ["-ば"]),
        ],
    },
    {
        "id": "-ちゃ",
        "name": "-ちゃ",
        "rules": [
            suffix_inflection("ちゃ", "る", ["v5"], ["v1"]),
            suffix_inflection("いじゃ", "ぐ", ["v5"], ["v5"]),
            suffix_inflection("いちゃ", "く", ["v5"], ["v5"]),
            suffix_inflection("しちゃ", "す", ["v5"], ["v5"]),
            suffix_inflection("っちゃ", "う", ["v5"], ["v5"]),
            suffix_inflection("っちゃ", "く", ["v5"], ["v5"]),
            suffix_inflection("っちゃ", "つ", ["v5"], ["v5"]),
            suffix_inflection("っちゃ", "る", ["v5"], ["v5"]),
            suffix_inflection("んじゃ", "ぬ", ["v5"], ["v5"]),
            suffix_inflection("んじゃ", "ぶ", ["v5"], ["v5"]),
            suffix_inflection("んじゃ", "む", ["v5"], ["v5"]),
            suffix_inflection("じちゃ", "ずる", ["v5"], ["vz"]),
            suffix_inflection("しちゃ", "する", ["v5"], ["vs"]),
            suffix_inflection("為ちゃ", "為る", ["v5"], ["vs"]),
            suffix_inflection("きちゃ", "くる", ["v5"], ["vk"]),
            suffix_inflection("来ちゃ", "来る", ["v5"], ["vk"]),
            suffix_inflection("來ちゃ", "來る", ["v5"], ["vk"]),
        ],
    },
    {
        "id": "-ちゃう",
        "name": "-ちゃう",
        "rules": [
            suffix_inflection("ちゃう", "る", ["v5"], ["v1"]),
            suffix_inflection("いじゃう", "ぐ", ["v5"], ["v5"]),
            suffix_inflection("いちゃう", "く", ["v5"], ["v5"]),
            suffix_inflection("しちゃう", "す", ["v5"], ["v5"]),
            suffix_inflection("っちゃう", "う", ["v5"], ["v5"]),
            suffix_inflection("っちゃう", "く", ["v5"], ["v5"]),
            suffix_inflection("っちゃう", "つ", ["v5"], ["v5"]),
            suffix_inflection("っちゃう", "る", ["v5"], ["v5"]),
            suffix_inflection("んじゃう", "ぬ", ["v5"], ["v5"]),
            suffix_inflection("んじゃう", "ぶ", ["v5"], ["v5"]),
            suffix_inflection("んじゃう", "む", ["v5"], ["v5"]),
            suffix_inflection("じちゃう", "ずる", ["v5"], ["vz"]),
            suffix_inflection("しちゃう", "する", ["v5"], ["vs"]),
            suffix_inflection("為ちゃう", "為る", ["v5"], ["vs"]),
            suffix_inflection("きちゃう", "くる", ["v5"], ["vk"]),
            suffix_inflection("来ちゃう", "来る", ["v5"], ["vk"]),
            suffix_inflection("來ちゃう", "來る", ["v5"], ["vk"]),
        ],
    },
    {
        "id": "-ちまう",
        "name": "-ちまう",
        "rules": [
            suffix_inflection("ちまう", "る", ["v5"], ["v1"]),
            suffix_inflection("いじまう", "ぐ", ["v5"], ["v5"]),
            suffix_inflection("いちまう", "く", ["v5"], ["v5"]),
            suffix_inflection("しちまう", "す", ["v5"], ["v5"]),
            suffix_inflection("っちまう", "う", ["v5"], ["v5"]),
            suffix_inflection("っちまう", "く", ["v5"], ["v5"]),
            suffix_inflection("っちまう", "つ", ["v5"], ["v5"]),
            suffix_inflection("っちまう", "る", ["v5"], ["v5"]),
            suffix_inflection("んじまう", "ぬ", ["v5"], ["v5"]),
            suffix_inflection("んじまう", "ぶ", ["v5"], ["v5"]),
            suffix_inflection("んじまう", "む", ["v5"], ["v5"]),
            suffix_inflection("じちまう", "ずる", ["v5"], ["vz"]),
            suffix_inflection("しちまう", "する", ["v5"], ["vs"]),
            suffix_inflection("為ちまう", "為る", ["v5"], ["vs"]),
            suffix_inflection("きちまう", "くる", ["v5"], ["vk"]),
            suffix_inflection("来ちまう", "来る", ["v5"], ["vk"]),
            suffix_inflection("來ちまう", "來る", ["v5"], ["vk"]),
        ],
    },
    {
        "id": "-しまう",
        "name": "-しまう",
        "rules": [
            suffix_inflection("てしまう", "て", ["v5"], ["-て"]),
            suffix_inflection("でしまう", "で", ["v5"], ["-て"]),
        ],
    },
    {
        "id": "-なさい",
        "name": "-なさい",
        "rules": [
            suffix_inflection("なさい", "る", ["-なさい"], ["v1"]),
            suffix_inflection("いなさい", "う", ["-なさい"], ["v5"]),
            suffix_inflection("きなさい", "く", ["-なさい"], ["v5"]),
            suffix_inflection("ぎなさい", "ぐ", ["-なさい"], ["v5"]),
            suffix_inflection("しなさい", "す", ["-なさい"], ["v5"]),
            suffix_inflection("ちなさい", "つ", ["-なさい"], ["v5"]),
            suffix_inflection("になさい", "ぬ", ["-なさい"], ["v5"]),
            suffix_inflection("びなさい", "ぶ", ["-なさい"], ["v5"]),
            suffix_inflection("みなさい", "む", ["-なさい"], ["v5"]),
            suffix_inflection("りなさい", "る", ["-なさい"], ["v5"]),
            suffix_inflection("じなさい", "ずる", ["-なさい"], ["vz"]),
            suffix_inflection("しなさい", "する", ["-なさい"], ["vs"]),
            suffix_inflection("為なさい", "為る", ["-なさい"], ["vs"]),
            suffix_inflection("きなさい", "くる", ["-なさい"], ["vk"]),
            suffix_inflection("来なさい", "来る", ["-なさい"], ["vk"]),
            suffix_inflection("來なさい", "來る", ["-なさい"], ["vk"]),
        ],
    },
    {
        "id": "-そう",
        "name": "-そう",
        "rules": [
            suffix_inflection("そう", "い", [], ["adj-i"]),
            suffix_inflection("そう", "る", [], ["v1"]),
            suffix_inflection("いそう", "う", [], ["v5"]),
            suffix_inflection("きそう", "く", [], ["v5"]),
            suffix_inflection("ぎそう", "ぐ", [], ["v5"]),
            suffix_inflection("しそう", "す", [], ["v5"]),
            suffix_inflection("ちそう", "つ", [], ["v5"]),
            suffix_inflection("にそう", "ぬ", [], ["v5"]),
            suffix_inflection("びそう", "ぶ", [], ["v5"]),
            suffix_inflection("みそう", "む", [], ["v5"]),
            suffix_inflection("りそう", "る", [], ["v5"]),
            suffix_inflection("じそう", "ずる", [], ["vz"]),
            suffix_inflection("しそう", "する", [], ["vs"]),
            suffix_inflection("為そう", "為る", [], ["vs"]),
            suffix_inflection("きそう", "くる", [], ["vk"]),
            suffix_inflection("来そう", "来る", [], ["vk"]),
            suffix_inflection("來そう", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "-すぎる",
        "name": "-すぎる",
        "rules": [
            suffix_inflection("すぎる", "い", ["v1"], ["adj-i"]),
            suffix_inflection("すぎる", "る", ["v1"], ["v1"]),
            suffix_inflection("いすぎる", "う", ["v1"], ["v5"]),
            suffix_inflection("きすぎる", "く", ["v1"], ["v5"]),
            suffix_inflection("ぎすぎる", "ぐ", ["v1"], ["v5"]),
            suffix_inflection("しすぎる", "す", ["v1"], ["v5"]),
            suffix_inflection("ちすぎる", "つ", ["v1"], ["v5"]),
            suffix_inflection("にすぎる", "ぬ", ["v1"], ["v5"]),
            suffix_inflection("びすぎる", "ぶ", ["v1"], ["v5"]),
            suffix_inflection("みすぎる", "む", ["v1"], ["v5"]),
            suffix_inflection("りすぎる", "る", ["v1"], ["v5"]),
            suffix_inflection("じすぎる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("しすぎる", "する", ["v1"], ["vs"]),
            suffix_inflection("為すぎる", "為る", ["v1"], ["vs"]),
            suffix_inflection("きすぎる", "くる", ["v1"], ["vk"]),
            suffix_inflection("来すぎる", "来る", ["v1"], ["vk"]),
            suffix_inflection("來すぎる", "來る", ["v1"], ["vk"]),
        ],
    },
    {
        "id": "-過ぎる",
        "name": "-過ぎる",
        "rules": [
            suffix_inflection("過ぎる", "い", ["v1"], ["adj-i"]),
            suffix_inflection("過ぎる", "る", ["v1"], ["v1"]),
            suffix_inflection("い過ぎる", "う", ["v1"], ["v5"]),
            suffix_inflection("き過ぎる", "く", ["v1"], ["v5"]),
            suffix_inflection("ぎ過ぎる", "ぐ", ["v1"], ["v5"]),
            suffix_inflection("し過ぎる", "す", ["v1"], ["v5"]),
            suffix_inflection("ち過ぎる", "つ", ["v1"], ["v5"]),
            suffix_inflection("に過ぎる", "ぬ", ["v1"], ["v5"]),
            suffix_inflection("び過ぎる", "ぶ", ["v1"], ["v5"]),
            suffix_inflection("み過ぎる", "む", ["v1"], ["v5"]),
            suffix_inflection("り過ぎる", "る", ["v1"], ["v5"]),
            suffix_inflection("じ過ぎる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("し過ぎる", "する", ["v1"], ["vs"]),
            suffix_inflection("為過ぎる", "為る", ["v1"], ["vs"]),
            suffix_inflection("き過ぎる", "くる", ["v1"], ["vk"]),
            suffix_inflection("来過ぎる", "来る", ["v1"], ["vk"]),
            suffix_inflection("來過ぎる", "來る", ["v1"], ["vk"]),
        ],
    },
    {
        "id": "-たい",
        "name": "-たい",
        "rules": [
            suffix_inflection("たい", "る", ["adj-i"], ["v1"]),
            suffix_inflection("いたい", "う", ["adj-i"], ["v5"]),
            suffix_inflection("きたい", "く", ["adj-i"], ["v5"]),
            suffix_inflection("ぎたい", "ぐ", ["adj-i"], ["v5"]),
            suffix_inflection("したい", "す", ["adj-i"], ["v5"]),
            suffix_inflection("ちたい", "つ", ["adj-i"], ["v5"]),
            suffix_inflection("にたい", "ぬ", ["adj-i"], ["v5"]),
            suffix_inflection("びたい", "ぶ", ["adj-i"], ["v5"]),
            suffix_inflection("みたい", "む", ["adj-i"], ["v5"]),
            suffix_inflection("りたい", "る", ["adj-i"], ["v5"]),
            suffix_inflection("じたい", "ずる", ["adj-i"], ["vz"]),
            suffix_inflection("したい", "する", ["adj-i"], ["vs"]),
            suffix_inflection("為たい", "為る", ["adj-i"], ["vs"]),
            suffix_inflection("きたい", "くる", ["adj-i"], ["vk"]),
            suffix_inflection("来たい", "来る", ["adj-i"], ["vk"]),
            suffix_inflection("來たい", "來る", ["adj-i"], ["vk"]),
        ],
    },
    {
        "id": "-たら",
        "name": "-たら",
        "rules": [
            suffix_inflection("かったら", "い", [], ["adj-i"]),
            suffix_inflection("たら", "る", [], ["v1"]),
            suffix_inflection("いたら", "く", [], ["v5"]),
            suffix_inflection("いだら", "ぐ", [], ["v5"]),
            suffix_inflection("したら", "す", [], ["v5"]),
            suffix_inflection("ったら", "う", [], ["v5"]),
            suffix_inflection("ったら", "つ", [], ["v5"]),
            suffix_inflection("ったら", "る", [], ["v5"]),
            suffix_inflection("んだら", "ぬ", [], ["v5"]),
            suffix_inflection("んだら", "ぶ", [], ["v5"]),
            suffix_inflection("んだら", "む", [], ["v5"]),
            suffix_inflection("じたら", "ずる", [], ["vz"]),
            suffix_inflection("したら", "する", [], ["vs"]),
            suffix_inflection("為たら", "為る", [], ["vs"]),
            suffix_inflection("きたら", "くる", [], ["vk"]),
            suffix_inflection("来たら", "来る", [], ["vk"]),
            suffix_inflection("來たら", "來る", [], ["vk"]),
            suffix_inflection("いったら", "いく", [], ["v5"]),
            suffix_inflection("行ったら", "行く", [], ["v5"]),
            suffix_inflection("逝ったら", "逝く", [], ["v5"]),
            suffix_inflection("往ったら", "往く", [], ["v5"]),
            suffix_inflection("こうたら", "こう", [], ["v5"]),
            suffix_inflection("とうたら", "とう", [], ["v5"]),
            suffix_inflection("請うたら", "請う", [], ["v5"]),
            suffix_inflection("乞うたら", "乞う", [], ["v5"]),
            suffix_inflection("恋うたら", "恋う", [], ["v5"]),
            suffix_inflection("問うたら", "問う", [], ["v5"]),
            suffix_inflection("訪うたら", "訪う", [], ["v5"]),
            suffix_inflection("宣うたら", "宣う", [], ["v5"]),
            suffix_inflection("曰うたら", "曰う", [], ["v5"]),
            suffix_inflection("給うたら", "給う", [], ["v5"]),
            suffix_inflection("賜うたら", "賜う", [], ["v5"]),
            suffix_inflection("揺蕩うたら", "揺蕩う", [], ["v5"]),
            suffix_inflection("のたもうたら", "のたまう", [], ["v5"]),
            suffix_inflection("たもうたら", "たまう", [], ["v5"]),
            suffix_inflection("たゆとうたら", "たゆたう", [], ["v5"]),
            suffix_inflection("ましたら", "ます", [], ["-ます"]),
        ],
    },
    {
        "id": "-たり",
        "name": "-たり",
        "rules": [
            suffix_inflection("かったり", "い", [], ["adj-i"]),
            suffix_inflection("たり", "る", [], ["v1"]),
            suffix_inflection("いたり", "く", [], ["v5"]),
            suffix_inflection("いだり", "ぐ", [], ["v5"]),
            suffix_inflection("したり", "す", [], ["v5"]),
            suffix_inflection("ったり", "う", [], ["v5"]),
            suffix_inflection("ったり", "つ", [], ["v5"]),
            suffix_inflection("ったり", "る", [], ["v5"]),
            suffix_inflection("んだり", "ぬ", [], ["v5"]),
            suffix_inflection("んだり", "ぶ", [], ["v5"]),
            suffix_inflection("んだり", "む", [], ["v5"]),
            suffix_inflection("じたり", "ずる", [], ["vz"]),
            suffix_inflection("したり", "する", [], ["vs"]),
            suffix_inflection("為たり", "為る", [], ["vs"]),
            suffix_inflection("きたり", "くる", [], ["vk"]),
            suffix_inflection("来たり", "来る", [], ["vk"]),
            suffix_inflection("來たり", "來る", [], ["vk"]),
            suffix_inflection("いったり", "いく", [], ["v5"]),
            suffix_inflection("行ったり", "行く", [], ["v5"]),
            suffix_inflection("逝ったり", "逝く", [], ["v5"]),
            suffix_inflection("往ったり", "往く", [], ["v5"]),
            suffix_inflection("こうたり", "こう", [], ["v5"]),
            suffix_inflection("とうたり", "とう", [], ["v5"]),
            suffix_inflection("請うたり", "請う", [], ["v5"]),
            suffix_inflection("乞うたり", "乞う", [], ["v5"]),
            suffix_inflection("恋うたり", "恋う", [], ["v5"]),
            suffix_inflection("問うたり", "問う", [], ["v5"]),
            suffix_inflection("訪うたり", "訪う", [], ["v5"]),
            suffix_inflection("宣うたり", "宣う", [], ["v5"]),
            suffix_inflection("曰うたり", "曰う", [], ["v5"]),
            suffix_inflection("給うたり", "給う", [], ["v5"]),
            suffix_inflection("賜うたり", "賜う", [], ["v5"]),
            suffix_inflection("揺蕩うたり", "揺蕩う", [], ["v5"]),
            suffix_inflection("のたもうたり", "のたまう", [], ["v5"]),
            suffix_inflection("たもうたり", "たまう", [], ["v5"]),
            suffix_inflection("たゆとうたり", "たゆたう", [], ["v5"]),
        ],
    },
    {
        "id": "-て",
        "name": "-て",
        "rules": [
            suffix_inflection("くて", "い", ["-て"], ["adj-i"]),
            suffix_inflection("て", "る", ["-て"], ["v1"]),
            suffix_inflection("いて", "く", ["-て"], ["v5"]),
            suffix_inflection("いで", "ぐ", ["-て"], ["v5"]),
            suffix_inflection("して", "す", ["-て"], ["v5"]),
            suffix_inflection("って", "う", ["-て"], ["v5"]),
            suffix_inflection("って", "つ", ["-て"], ["v5"]),
            suffix_inflection("って", "る", ["-て"], ["v5"]),
            suffix_inflection("んで", "ぬ", ["-て"], ["v5"]),
            suffix_inflection("んで", "ぶ", ["-て"], ["v5"]),
            suffix_inflection("んで", "む", ["-て"], ["v5"]),
            suffix_inflection("じて", "ずる", ["-て"], ["vz"]),
            suffix_inflection("して", "する", ["-て"], ["vs"]),
            suffix_inflection("為て", "為る", ["-て"], ["vs"]),
            suffix_inflection("きて", "くる", ["-て"], ["vk"]),
            suffix_inflection("来て", "来る", ["-て"], ["vk"]),
            suffix_inflection("來て", "來る", ["-て"], ["vk"]),
            suffix_inflection("いって", "いく", ["-て"], ["v5"]),
            suffix_inflection("行って", "行く", ["-て"], ["v5"]),
            suffix_inflection("逝って", "逝く", ["-て"], ["v5"]),
            suffix_inflection("往って", "往く", ["-て"], ["v5"]),
            suffix_inflection("こうて", "こう", ["-て"], ["v5"]),
            suffix_inflection("とうて", "とう", ["-て"], ["v5"]),
            suffix_inflection("請うて", "請う", ["-て"], ["v5"]),
            suffix_inflection("乞うて", "乞う", ["-て"], ["v5"]),
            suffix_inflection("恋うて", "恋う", ["-て"], ["v5"]),
            suffix_inflection("問うて", "問う", ["-て"], ["v5"]),
            suffix_inflection("訪うて", "訪う", ["-て"], ["v5"]),
            suffix_inflection("宣うて", "宣う", ["-て"], ["v5"]),
            suffix_inflection("曰うて", "曰う", ["-て"], ["v5"]),
            suffix_inflection("給うて", "給う", ["-て"], ["v5"]),
            suffix_inflection("賜うて", "賜う", ["-て"], ["v5"]),
            suffix_inflection("揺蕩うて", "揺蕩う", ["-て"], ["v5"]),
            suffix_inflection("のたもうて", "のたまう", ["-て"], ["v5"]),
            suffix_inflection("たもうて", "たまう", ["-て"], ["v5"]),
            suffix_inflection("たゆとうて", "たゆたう", ["-て"], ["v5"]),
            suffix_inflection("まして", "ます", [], ["-ます"]),
        ],
    },
    {
        "id": "-ず",
        "name": "-ず",
        "rules": [
            suffix_inflection("ず", "る", [], ["v1"]),
            suffix_inflection("かず", "く", [], ["v5"]),
            suffix_inflection("がず", "ぐ", [], ["v5"]),
            suffix_inflection("さず", "す", [], ["v5"]),
            suffix_inflection("たず", "つ", [], ["v5"]),
            suffix_inflection("なず", "ぬ", [], ["v5"]),
            suffix_inflection("ばず", "ぶ", [], ["v5"]),
            suffix_inflection("まず", "む", [], ["v5"]),
            suffix_inflection("らず", "る", [], ["v5"]),
            suffix_inflection("わず", "う", [], ["v5"]),
            suffix_inflection("ぜず", "ずる", [], ["vz"]),
            suffix_inflection("せず", "する", [], ["vs"]),
            suffix_inflection("為ず", "為る", [], ["vs"]),
            suffix_inflection("こず", "くる", [], ["vk"]),
            suffix_inflection("来ず", "来る", [], ["vk"]),
            suffix_inflection("來ず", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "-ぬ",
        "name": "-ぬ",
        "rules": [
            suffix_inflection("ぬ", "る", [], ["v1"]),
            suffix_inflection("かぬ", "く", [], ["v5"]),
            suffix_inflection("がぬ", "ぐ", [], ["v5"]),
            suffix_inflection("さぬ", "す", [], ["v5"]),
            suffix_inflection("たぬ", "つ", [], ["v5"]),
            suffix_inflection("なぬ", "ぬ", [], ["v5"]),
            suffix_inflection("ばぬ", "ぶ", [], ["v5"]),
            suffix_inflection("まぬ", "む", [], ["v5"]),
            suffix_inflection("らぬ", "る", [], ["v5"]),
            suffix_inflection("わぬ", "う", [], ["v5"]),
            suffix_inflection("ぜぬ", "ずる", [], ["vz"]),
            suffix_inflection("せぬ", "する", [], ["vs"]),
            suffix_inflection("為ぬ", "為る", [], ["vs"]),
            suffix_inflection("こぬ", "くる", [], ["vk"]),
            suffix_inflection("来ぬ", "来る", [], ["vk"]),
            suffix_inflection("來ぬ", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "-ん",
        "name": "-ん",
        "rules": [
            suffix_inflection("ん", "る", ["-ん"], ["v1"]),
            suffix_inflection("かん", "く", ["-ん"], ["v5"]),
            suffix_inflection("がん", "ぐ", ["-ん"], ["v5"]),
            suffix_inflection("さん", "す", ["-ん"], ["v5"]),
            suffix_inflection("たん", "つ", ["-ん"], ["v5"]),
            suffix_inflection("なん", "ぬ", ["-ん"], ["v5"]),
            suffix_inflection("ばん", "ぶ", ["-ん"], ["v5"]),
            suffix_inflection("まん", "む", ["-ん"], ["v5"]),
            suffix_inflection("らん", "る", ["-ん"], ["v5"]),
            suffix_inflection("わん", "う", ["-ん"], ["v5"]),
            suffix_inflection("ぜん", "ずる", ["-ん"], ["vz"]),
            suffix_inflection("せん", "する", ["-ん"], ["vs"]),
            suffix_inflection("為ん", "為る", ["-ん"], ["vs"]),
            suffix_inflection("こん", "くる", ["-ん"], ["vk"]),
            suffix_inflection("来ん", "来る", ["-ん"], ["vk"]),
            suffix_inflection("來ん", "來る", ["-ん"], ["vk"]),
        ],
    },
    {
        "id": "-んばかり",
        "name": "-んばかり",
        "rules": [
            suffix_inflection("んばかり", "る", [], ["v1"]),
            suffix_inflection("かんばかり", "く", [], ["v5"]),
            suffix_inflection("がんばかり", "ぐ", [], ["v5"]),
            suffix_inflection("さんばかり", "す", [], ["v5"]),
            suffix_inflection("たんばかり", "つ", [], ["v5"]),
            suffix_inflection("なんばかり", "ぬ", [], ["v5"]),
            suffix_inflection("ばんばかり", "ぶ", [], ["v5"]),
            suffix_inflection("まんばかり", "む", [], ["v5"]),
            suffix_inflection("らんばかり", "る", [], ["v5"]),
            suffix_inflection("わんばかり", "う", [], ["v5"]),
            suffix_inflection("ぜんばかり", "ずる", [], ["vz"]),
            suffix_inflection("せんばかり", "する", [], ["vs"]),
            suffix_inflection("為んばかり", "為る", [], ["vs"]),
            suffix_inflection("こんばかり", "くる", [], ["vk"]),
            suffix_inflection("来んばかり", "来る", [], ["vk"]),
            suffix_inflection("來んばかり", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "-んとする",
        "name": "-んとする",
        "rules": [
            suffix_inflection("んとする", "る", ["vs"], ["v1"]),
            suffix_inflection("かんとする", "く", ["vs"], ["v5"]),
            suffix_inflection("がんとする", "ぐ", ["vs"], ["v5"]),
            suffix_inflection("さんとする", "す", ["vs"], ["v5"]),
            suffix_inflection("たんとする", "つ", ["vs"], ["v5"]),
            suffix_inflection("なんとする", "ぬ", ["vs"], ["v5"]),
            suffix_inflection("ばんとする", "ぶ", ["vs"], ["v5"]),
            suffix_inflection("まんとする", "む", ["vs"], ["v5"]),
            suffix_inflection("らんとする", "る", ["vs"], ["v5"]),
            suffix_inflection("わんとする", "う", ["vs"], ["v5"]),
            suffix_inflection("ぜんとする", "ずる", ["vs"], ["vz"]),
            suffix_inflection("せんとする", "する", ["vs"], ["vs"]),
            suffix_inflection("為んとする", "為る", ["vs"], ["vs"]),
            suffix_inflection("こんとする", "くる", ["vs"], ["vk"]),
            suffix_inflection("来んとする", "来る", ["vs"], ["vk"]),
            suffix_inflection("來んとする", "來る", ["vs"], ["vk"]),
        ],
    },
    {
        "id": "-む",
        "name": "-む",
        "rules": [
            suffix_inflection("む", "る", [], ["v1"]),
            suffix_inflection("かむ", "く", [], ["v5"]),
            suffix_inflection("がむ", "ぐ", [], ["v5"]),
            suffix_inflection("さむ", "す", [], ["v5"]),
            suffix_inflection("たむ", "つ", [], ["v5"]),
            suffix_inflection("なむ", "ぬ", [], ["v5"]),
            suffix_inflection("ばむ", "ぶ", [], ["v5"]),
            suffix_inflection("まむ", "む", [], ["v5"]),
            suffix_inflection("らむ", "る", [], ["v5"]),
            suffix_inflection("わむ", "う", [], ["v5"]),
            suffix_inflection("ぜむ", "ずる", [], ["vz"]),
            suffix_inflection("せむ", "する", [], ["vs"]),
            suffix_inflection("為む", "為る", [], ["vs"]),
            suffix_inflection("こむ", "くる", [], ["vk"]),
            suffix_inflection("来む", "来る", [], ["vk"]),
            suffix_inflection("來む", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "-ざる",
        "name": "-ざる",
        "rules": [
            suffix_inflection("ざる", "る", [], ["v1"]),
            suffix_inflection("かざる", "く", [], ["v5"]),
            suffix_inflection("がざる", "ぐ", [], ["v5"]),
            suffix_inflection("さざる", "す", [], ["v5"]),
            suffix_inflection("たざる", "つ", [], ["v5"]),
            suffix_inflection("なざる", "ぬ", [], ["v5"]),
            suffix_inflection("ばざる", "ぶ", [], ["v5"]),
            suffix_inflection("まざる", "む", [], ["v5"]),
            suffix_inflection("らざる", "る", [], ["v5"]),
            suffix_inflection("わざる", "う", [], ["v5"]),
            suffix_inflection("ぜざる", "ずる", [], ["vz"]),
            suffix_inflection("せざる", "する", [], ["vs"]),
            suffix_inflection("為ざる", "為る", [], ["vs"]),
            suffix_inflection("こざる", "くる", [], ["vk"]),
            suffix_inflection("来ざる", "来る", [], ["vk"]),
            suffix_inflection("來ざる", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "-ねば",
        "name": "-ねば",
        "rules": [
            suffix_inflection("ねば", "る", ["-ば"], ["v1"]),
            suffix_inflection("かねば", "く", ["-ば"], ["v5"]),
            suffix_inflection("がねば", "ぐ", ["-ば"], ["v5"]),
            suffix_inflection("さねば", "す", ["-ば"], ["v5"]),
            suffix_inflection("たねば", "つ", ["-ば"], ["v5"]),
            suffix_inflection("なねば", "ぬ", ["-ば"], ["v5"]),
            suffix_inflection("ばねば", "ぶ", ["-ば"], ["v5"]),
            suffix_inflection("まねば", "む", ["-ば"], ["v5"]),
            suffix_inflection("らねば", "る", ["-ば"], ["v5"]),
            suffix_inflection("わねば", "う", ["-ば"], ["v5"]),
            suffix_inflection("ぜねば", "ずる", ["-ば"], ["vz"]),
            suffix_inflection("せねば", "する", ["-ば"], ["vs"]),
            suffix_inflection("為ねば", "為る", ["-ば"], ["vs"]),
            suffix_inflection("こねば", "くる", ["-ば"], ["vk"]),
            suffix_inflection("来ねば", "来る", ["-ば"], ["vk"]),
            suffix_inflection("來ねば", "來る", ["-ば"], ["vk"]),
        ],
    },
    {
        "id": "-く",
        "name": "-く",
        "rules": [
            suffix_inflection("く", "い", ["-く"], ["adj-i"]),
        ],
    },
    {
        "id": "causative",
        "name": "causative",
        "rules": [
            suffix_inflection("させる", "る", ["v1"], ["v1"]),
            suffix_inflection("かせる", "く", ["v1"], ["v5"]),
            suffix_inflection("がせる", "ぐ", ["v1"], ["v5"]),
            suffix_inflection("させる", "す", ["v1"], ["v5"]),
            suffix_inflection("たせる", "つ", ["v1"], ["v5"]),
            suffix_inflection("なせる", "ぬ", ["v1"], ["v5"]),
            suffix_inflection("ばせる", "ぶ", ["v1"], ["v5"]),
            suffix_inflection("ませる", "む", ["v1"], ["v5"]),
            suffix_inflection("らせる", "る", ["v1"], ["v5"]),
            suffix_inflection("わせる", "う", ["v1"], ["v5"]),
            suffix_inflection("じさせる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("ぜさせる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("させる", "する", ["v1"], ["vs"]),
            suffix_inflection("為せる", "為る", ["v1"], ["vs"]),
            suffix_inflection("せさせる", "する", ["v1"], ["vs"]),
            suffix_inflection("為させる", "為る", ["v1"], ["vs"]),
            suffix_inflection("こさせる", "くる", ["v1"], ["vk"]),
            suffix_inflection("来させる", "来る", ["v1"], ["vk"]),
            suffix_inflection("來させる", "來る", ["v1"], ["vk"]),
        ],
    },
    {
        "id": "short causative",
        "name": "short causative",
        "rules": [
            suffix_inflection("さす", "る", ["v5ss"], ["v1"]),
            suffix_inflection("かす", "く", ["v5sp"], ["v5"]),
            suffix_inflection("がす", "ぐ", ["v5sp"], ["v5"]),
            suffix_inflection("さす", "す", ["v5ss"], ["v5"]),
            suffix_inflection("たす", "つ", ["v5sp"], ["v5"]),
            suffix_inflection("なす", "ぬ", ["v5sp"], ["v5"]),
            suffix_inflection("ばす", "ぶ", ["v5sp"], ["v5"]),
            suffix_inflection("ます", "む", ["v5sp"], ["v5"]),
            suffix_inflection("らす", "る", ["v5sp"], ["v5"]),
            suffix_inflection("わす", "う", ["v5sp"], ["v5"]),
            suffix_inflection("じさす", "ずる", ["v5ss"], ["vz"]),
            suffix_inflection("ぜさす", "ずる", ["v5ss"], ["vz"]),
            suffix_inflection("さす", "する", ["v5ss"], ["vs"]),
            suffix_inflection("為す", "為る", ["v5ss"], ["vs"]),
            suffix_inflection("こさす", "くる", ["v5ss"], ["vk"]),
            suffix_inflection("来さす", "来る", ["v5ss"], ["vk"]),
            suffix_inflection("來さす", "來る", ["v5ss"], ["vk"]),
        ],
    },
    {
        "id": "imperative",
        "name": "imperative",
        "rules": [
            suffix_inflection("ろ", "る", [], ["v1"]),
            suffix_inflection("よ", "る", [], ["v1"]),
            suffix_inflection("え", "う", [], ["v5"]),
            suffix_inflection("け", "く", [], ["v5"]),
            suffix_inflection("げ", "ぐ", [], ["v5"]),
            suffix_inflection("せ", "す", [], ["v5"]),
            suffix_inflection("て", "つ", [], ["v5"]),
            suffix_inflection("ね", "ぬ", [], ["v5"]),
            suffix_inflection("べ", "ぶ", [], ["v5"]),
            suffix_inflection("め", "む", [], ["v5"]),
            suffix_inflection("れ", "る", [], ["v5"]),
            suffix_inflection("じろ", "ずる", [], ["vz"]),
            suffix_inflection("ぜよ", "ずる", [], ["vz"]),
            suffix_inflection("しろ", "する", [], ["vs"]),
            suffix_inflection("せよ", "する", [], ["vs"]),
            suffix_inflection("為ろ", "為る", [], ["vs"]),
            suffix_inflection("為よ", "為る", [], ["vs"]),
            suffix_inflection("こい", "くる", [], ["vk"]),
            suffix_inflection("来い", "来る", [], ["vk"]),
            suffix_inflection("來い", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "continuative",
        "name": "continuative",
        "rules": [
            suffix_inflection("い", "いる", [], ["v1d"]),
            suffix_inflection("え", "える", [], ["v1d"]),
            suffix_inflection("き", "きる", [], ["v1d"]),
            suffix_inflection("ぎ", "ぎる", [], ["v1d"]),
            suffix_inflection("け", "ける", [], ["v1d"]),
            suffix_inflection("げ", "げる", [], ["v1d"]),
            suffix_inflection("じ", "じる", [], ["v1d"]),
            suffix_inflection("せ", "せる", [], ["v1d"]),
            suffix_inflection("ぜ", "ぜる", [], ["v1d"]),
            suffix_inflection("ち", "ちる", [], ["v1d"]),
            suffix_inflection("て", "てる", [], ["v1d"]),
            suffix_inflection("で", "でる", [], ["v1d"]),
            suffix_inflection("に", "にる", [], ["v1d"]),
            suffix_inflection("ね", "ねる", [], ["v1d"]),
            suffix_inflection("ひ", "ひる", [], ["v1d"]),
            suffix_inflection("び", "びる", [], ["v1d"]),
            suffix_inflection("へ", "へる", [], ["v1d"]),
            suffix_inflection("べ", "べる", [], ["v1d"]),
            suffix_inflection("み", "みる", [], ["v1d"]),
            suffix_inflection("め", "める", [], ["v1d"]),
            suffix_inflection("り", "りる", [], ["v1d"]),
            suffix_inflection("れ", "れる", [], ["v1d"]),
            suffix_inflection("い", "う", [], ["v5"]),
            suffix_inflection("き", "く", [], ["v5"]),
            suffix_inflection("ぎ", "ぐ", [], ["v5"]),
            suffix_inflection("し", "す", [], ["v5"]),
            suffix_inflection("ち", "つ", [], ["v5"]),
            suffix_inflection("に", "ぬ", [], ["v5"]),
            suffix_inflection("び", "ぶ", [], ["v5"]),
            suffix_inflection("み", "む", [], ["v5"]),
            suffix_inflection("り", "る", [], ["v5"]),
            suffix_inflection("き", "くる", [], ["vk"]),
            suffix_inflection("し", "する", [], ["vs"]),
            suffix_inflection("来", "来る", [], ["vk"]),
            suffix_inflection("來", "來る", [], ["vk"]),
        ],
    },
    {
        "id": "negative",
        "name": "negative",
        "rules": [
            suffix_inflection("くない", "い", ["adj-i"], ["adj-i"]),
            suffix_inflection("ない", "る", ["adj-i"], ["v1"]),
            suffix_inflection("かない", "く", ["adj-i"], ["v5"]),
            suffix_inflection("がない", "ぐ", ["adj-i"], ["v5"]),
            suffix_inflection("さない", "す", ["adj-i"], ["v5"]),
            suffix_inflection("たない", "つ", ["adj-i"], ["v5"]),
            suffix_inflection("なない", "ぬ", ["adj-i"], ["v5"]),
            suffix_inflection("ばない", "ぶ", ["adj-i"], ["v5"]),
            suffix_inflection("まない", "む", ["adj-i"], ["v5"]),
            suffix_inflection("らない", "る", ["adj-i"], ["v5"]),
            suffix_inflection("わない", "う", ["adj-i"], ["v5"]),
            suffix_inflection("じない", "ずる", ["adj-i"], ["vz"]),
            suffix_inflection("しない", "する", ["adj-i"], ["vs"]),
            suffix_inflection("為ない", "為る", ["adj-i"], ["vs"]),
            suffix_inflection("こない", "くる", ["adj-i"], ["vk"]),
            suffix_inflection("来ない", "来る", ["adj-i"], ["vk"]),
            suffix_inflection("來ない", "來る", ["adj-i"], ["vk"]),
            suffix_inflection("ません", "ます", ["-ません"], ["-ます"]),
        ],
    },
    {
        "id": "-さ",
        "name": "-さ",
        "rules": [
            suffix_inflection("さ", "い", [], ["adj-i"]),
        ],
    },
    {
        "id": "passive",
        "name": "passive",
        "rules": [
            suffix_inflection("かれる", "く", ["v1"], ["v5"]),
            suffix_inflection("がれる", "ぐ", ["v1"], ["v5"]),
            suffix_inflection("される", "す", ["v1"], ["v5d", "v5sp"]),
            suffix_inflection("たれる", "つ", ["v1"], ["v5"]),
            suffix_inflection("なれる", "ぬ", ["v1"], ["v5"]),
            suffix_inflection("ばれる", "ぶ", ["v1"], ["v5"]),
            suffix_inflection("まれる", "む", ["v1"], ["v5"]),
            suffix_inflection("われる", "う", ["v1"], ["v5"]),
            suffix_inflection("られる", "る", ["v1"], ["v5"]),
            suffix_inflection("じされる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("ぜされる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("される", "する", ["v1"], ["vs"]),
            suffix_inflection("為れる", "為る", ["v1"], ["vs"]),
            suffix_inflection("こられる", "くる", ["v1"], ["vk"]),
            suffix_inflection("来られる", "来る", ["v1"], ["vk"]),
            suffix_inflection("來られる", "來る", ["v1"], ["vk"]),
        ],
    },
    {
        "id": "-た",
        "name": "-た",
        "rules": [
            suffix_inflection("かった", "い", ["-た"], ["adj-i"]),
            suffix_inflection("た", "る", ["-た"], ["v1"]),
            suffix_inflection("いた", "く", ["-た"], ["v5"]),
            suffix_inflection("いだ", "ぐ", ["-た"], ["v5"]),
            suffix_inflection("した", "す", ["-た"], ["v5"]),
            suffix_inflection("った", "う", ["-た"], ["v5"]),
            suffix_inflection("った", "つ", ["-た"], ["v5"]),
            suffix_inflection("った", "る", ["-た"], ["v5"]),
            suffix_inflection("んだ", "ぬ", ["-た"], ["v5"]),
            suffix_inflection("んだ", "ぶ", ["-た"], ["v5"]),
            suffix_inflection("んだ", "む", ["-た"], ["v5"]),
            suffix_inflection("じた", "ずる", ["-た"], ["vz"]),
            suffix_inflection("した", "する", ["-た"], ["vs"]),
            suffix_inflection("為た", "為る", ["-た"], ["vs"]),
            suffix_inflection("きた", "くる", ["-た"], ["vk"]),
            suffix_inflection("来た", "来る", ["-た"], ["vk"]),
            suffix_inflection("來た", "來る", ["-た"], ["vk"]),
            suffix_inflection("いった", "いく", ["-た"], ["v5"]),
            suffix_inflection("行った", "行く", ["-た"], ["v5"]),
            suffix_inflection("逝った", "逝く", ["-た"], ["v5"]),
            suffix_inflection("往った", "往く", ["-た"], ["v5"]),
            suffix_inflection("こうた", "こう", ["-た"], ["v5"]),
            suffix_inflection("とうた", "とう", ["-た"], ["v5"]),
            suffix_inflection("請うた", "請う", ["-た"], ["v5"]),
            suffix_inflection("乞うた", "乞う", ["-た"], ["v5"]),
            suffix_inflection("恋うた", "恋う", ["-た"], ["v5"]),
            suffix_inflection("問うた", "問う", ["-た"], ["v5"]),
            suffix_inflection("訪うた", "訪う", ["-た"], ["v5"]),
            suffix_inflection("宣うた", "宣う", ["-た"], ["v5"]),
            suffix_inflection("曰うた", "曰う", ["-た"], ["v5"]),
            suffix_inflection("給うた", "給う", ["-た"], ["v5"]),
            suffix_inflection("賜うた", "賜う", ["-た"], ["v5"]),
            suffix_inflection("揺蕩うた", "揺蕩う", ["-た"], ["v5"]),
            suffix_inflection("のたもうた", "のたまう", ["-た"], ["v5"]),
            suffix_inflection("たもうた", "たまう", ["-た"], ["v5"]),
            suffix_inflection("たゆとうた", "たゆたう", ["-た"], ["v5"]),
            suffix_inflection("ました", "ます", ["-た"], ["-ます"]),
            suffix_inflection("でした", "", ["-た"], ["-ません"]),
            suffix_inflection("かった", "", ["-た"], ["-ません", "-ん"]),
        ],
    },
    {
        "id": "-ます",
        "name": "-ます",
        "rules": [
            suffix_inflection("ます", "る", ["-ます"], ["v1"]),
            whole_word_inflection("いらっしゃいます", "いらっしゃる", ["-ます"], ["v5d"]),
            whole_word_inflection("ございます", "ござる", ["-ます"], ["v5d"]),
            whole_word_inflection("なさいます", "なさる", ["-ます"], ["v5d"]),
            whole_word_inflection("くださいます", "くださる", ["-ます"], ["v5d"]),
            whole_word_inflection("下さいます", "下さる", ["-ます"], ["v5d"]),
            whole_word_inflection("おっしゃいます", "おっしゃる", ["-ます"], ["v5d"]),
            whole_word_inflection("仰います", "仰る", ["-ます"], ["v5d"]),
            whole_word_inflection("仰有います", "仰有る", ["-ます"], ["v5d"]),
            suffix_inflection("います", "う", ["-ます"], ["v5d"]),
            suffix_inflection("きます", "く", ["-ます"], ["v5d"]),
            suffix_inflection("ぎます", "ぐ", ["-ます"], ["v5d"]),
            suffix_inflection("します", "す", ["-ます"], ["v5d", "v5s"]),
            suffix_inflection("ちます", "つ", ["-ます"], ["v5d"]),
            suffix_inflection("にます", "ぬ", ["-ます"], ["v5d"]),
            suffix_inflection("びます", "ぶ", ["-ます"], ["v5d"]),
            suffix_inflection("みます", "む", ["-ます"], ["v5d"]),
            suffix_inflection("ります", "る", ["-ます"], ["v5d"]),
            suffix_inflection("じます", "ずる", ["-ます"], ["vz"]),
            suffix_inflection("します", "する", ["-ます"], ["vs"]),
            suffix_inflection("為ます", "為る", ["-ます"], ["vs"]),
            suffix_inflection("きます", "くる", ["-ます"], ["vk"]),
            suffix_inflection("来ます", "来る", ["-ます"], ["vk"]),
            suffix_inflection("來ます", "來る", ["-ます"], ["vk"]),
            suffix_inflection("くあります", "い", ["-ます"], ["adj-i"]),
        ],
    },
    {
        "id": "potential",
        "name": "potential",
        "rules": [
            suffix_inflection("れる", "る", ["v1"], ["v1", "v5d"]),
            suffix_inflection("える", "う", ["v1"], ["v5d"]),
            suffix_inflection("ける", "く", ["v1"], ["v5d"]),
            suffix_inflection("げる", "ぐ", ["v1"], ["v5d"]),
            suffix_inflection("せる", "す", ["v1"], ["v5d"]),
            suffix_inflection("てる", "つ", ["v1"], ["v5d"]),
            suffix_inflection("ねる", "ぬ", ["v1"], ["v5d"]),
            suffix_inflection("べる", "ぶ", ["v1"], ["v5d"]),
            suffix_inflection("める", "む", ["v1"], ["v5d"]),
            suffix_inflection("できる", "する", ["v1"], ["vs"]),
            suffix_inflection("出来る", "する", ["v1"], ["vs"]),
            suffix_inflection("これる", "くる", ["v1"], ["vk"]),
            suffix_inflection("来れる", "来る", ["v1"], ["vk"]),
            suffix_inflection("來れる", "來る", ["v1"], ["vk"]),
        ],
    },
    {
        "id": "potential or passive",
        "name": "potential or passive",
        "rules": [
            suffix_inflection("られる", "る", ["v1"], ["v1"]),
            suffix_inflection("ざれる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("ぜられる", "ずる", ["v1"], ["vz"]),
            suffix_inflection("せられる", "する", ["v1"], ["vs"]),
            suffix_inflection("為られる", "為る", ["v1"], ["vs"]),
            suffix_inflection("こられる", "くる", ["v1"], ["vk"]),
            suffix_inflection("来られる", "来る", ["v1"], ["vk"]),
            suffix_inflection("來られる", "來る", ["v1"], ["vk"]),
        ],
    },
    {
        "id": "volitional",
        "name": "volitional",
        "rules": [
            suffix_inflection("よう", "る", [], ["v1"]),
            suffix_inflection("おう", "う", [], ["v5"]),
            suffix_inflection("こう", "く", [], ["v5"]),
            suffix_inflection("ごう", "ぐ", [], ["v5"]),
            suffix_inflection("そう", "す", [], ["v5"]),
            suffix_inflection("とう", "つ", [], ["v5"]),
            suffix_inflection("のう", "ぬ", [], ["v5"]),
            suffix_inflection("ぼう", "ぶ", [], ["v5"]),
            suffix_inflection("もう", "む", [], ["v5"]),
            suffix_inflection("ろう", "る", [], ["v5"]),
            suffix_inflection("じよう", "ずる", [], ["vz"]),
            suffix_inflection("しよう", "する", [], ["vs"]),
            suffix_inflection("為よう", "為る", [], ["vs"]),
            suffix_inflection("こよう", "くる", [], ["vk"]),
            suffix_inflection("来よう", "来る", [], ["vk"]),
            suffix_inflection("來よう", "來る", [], ["vk"]),
            suffix_inflection("ましょう", "ます", [], ["-ます"]),
            suffix_inflection("かろう", "い", [], ["adj-i"]),
        ],
    },
    {
        "id": "volitional slang",
        "name": "volitional slang",
        "rules": [
            suffix_inflection("よっか", "る", [], ["v1"]),
            suffix_inflection("おっか", "う", [], ["v5"]),
            suffix_inflection("こっか", "く", [], ["v5"]),
            suffix_inflection("ごっか", "ぐ", [], ["v5"]),
            suffix_inflection("そっか", "す", [], ["v5"]),
            suffix_inflection("とっか", "つ", [], ["v5"]),
            suffix_inflection("のっか", "ぬ", [], ["v5"]),
            suffix_inflection("ぼっか", "ぶ", [], ["v5"]),
            suffix_inflection("もっか", "む", [], ["v5"]),
            suffix_inflection("ろっか", "る", [], ["v5"]),
            suffix_inflection("じよっか", "ずる", [], ["vz"]),
            suffix_inflection("しよっか", "する", [], ["vs"]),
            suffix_inflection("為よっか", "為る", [], ["vs"]),
            suffix_inflection("こよっか", "くる", [], ["vk"]),
            suffix_inflection("来よっか", "来る", [], ["vk"]),
            suffix_inflection("來よっか", "來る", [], ["vk"]),
            suffix_inflection("ましょっか", "ます", [], ["-ます"]),
        ],
    },
    {
        "id": "-まい",
        "name": "-まい",
        "rules": [
            suffix_inflection("まい", "", [], ["v"]),
            suffix_inflection("まい", "る", [], ["v1"]),
            suffix_inflection("じまい", "ずる", [], ["vz"]),
            suffix_inflection("しまい", "する", [], ["vs"]),
            suffix_inflection("為まい", "為る", [], ["vs"]),
            suffix_inflection("こまい", "くる", [], ["vk"]),
            suffix_inflection("来まい", "来る", [], ["vk"]),
            suffix_inflection("來まい", "來る", [], ["vk"]),
            suffix_inflection("まい", "", [], ["-ます"]),
        ],
    },
    {
        "id": "-おく",
        "name": "-おく",
        "rules": [
            suffix_inflection("ておく", "て", ["v5"], ["-て"]),
            suffix_inflection("でおく", "で", ["v5"], ["-て"]),
            suffix_inflection("とく", "て", ["v5"], ["-て"]),
            suffix_inflection("どく", "で", ["v5"], ["-て"]),
            suffix_inflection("ないでおく", "ない", ["v5"], ["adj-i"]),
            suffix_inflection("ないどく", "ない", ["v5"], ["adj-i"]),
        ],
    },
    {
        "id": "-いる",
        "name": "-いる",
        "rules": [
            suffix_inflection("ている", "て", ["v1"], ["-て"]),
            suffix_inflection("ておる", "て", ["v5"], ["-て"]),
            suffix_inflection("てる", "て", ["v1p"], ["-て"]),
            suffix_inflection("でいる", "で", ["v1"], ["-て"]),
            suffix_inflection("でおる", "で", ["v5"], ["-て"]),
            suffix_inflection("でる", "で", ["v1p"], ["-て"]),
            suffix_inflection("とる", "て", ["v5"], ["-て"]),
            suffix_inflection("ないでいる", "ない", ["v1"], ["adj-i"]),
        ],
    },
    {
        "id": "-き",
        "name": "-き",
        "rules": [
            suffix_inflection("き", "い", [], ["adj-i"]),
        ],
    },
    {
        "id": "-げ",
        "name": "-げ",
        "rules": [
            suffix_inflection("げ", "い", [], ["adj-i"]),
            suffix_inflection("気", "い", [], ["adj-i"]),
        ],
    },
    {
        "id": "-がる",
        "name": "-がる",
        "rules": [
            suffix_inflection("がる", "い", ["v5"], ["adj-i"]),
        ],
    },
    {
        "id": "-やがる",
        "name": "-やがる",
        "rules": [
            suffix_inflection("やがる", "る", ["v5"], ["v1"]),
            suffix_inflection("いやがる", "う", ["v5"], ["v5"]),
            suffix_inflection("きやがる", "く", ["v5"], ["v5"]),
            suffix_inflection("ぎやがる", "ぐ", ["v5"], ["v5"]),
            suffix_inflection("しやがる", "す", ["v5"], ["v5"]),
            suffix_inflection("ちやがる", "つ", ["v5"], ["v5"]),
            suffix_inflection("にやがる", "ぬ", ["v5"], ["v5"]),
            suffix_inflection("びやがる", "ぶ", ["v5"], ["v5"]),
            suffix_inflection("みやがる", "む", ["v5"], ["v5"]),
            suffix_inflection("りやがる", "る", ["v5"], ["v5"]),
            suffix_inflection("じやがる", "ずる", ["v5"], ["vz"]),
            suffix_inflection("しやがる", "する", ["v5"], ["vs"]),
            suffix_inflection("為やがる", "為る", ["v5"], ["vs"]),
            suffix_inflection("きやがる", "くる", ["v5"], ["vk"]),
            suffix_inflection("来やがる", "来る", ["v5"], ["vk"]),
            suffix_inflection("來やがる", "來る", ["v5"], ["vk"]),
        ],
    },
    {
        "id": "-え",
        "name": "-え",
        "rules": [
            suffix_inflection("ねえ", "ない", [], ["adj-i"]),
            suffix_inflection("めえ", "むい", [], ["adj-i"]),
            suffix_inflection("みい", "むい", [], ["adj-i"]),
            suffix_inflection("ちぇえ", "つい", [], ["adj-i"]),
            suffix_inflection("ちい", "つい", [], ["adj-i"]),
            suffix_inflection("せえ", "すい", [], ["adj-i"]),
            suffix_inflection("ええ", "いい", [], ["adj-i"]),
            suffix_inflection("ええ", "わい", [], ["adj-i"]),
            suffix_inflection("ええ", "よい", [], ["adj-i"]),
            suffix_inflection("いぇえ", "よい", [], ["adj-i"]),
            suffix_inflection("うぇえ", "わい", [], ["adj-i"]),
            suffix_inflection("けえ", "かい", [], ["adj-i"]),
            suffix_inflection("げえ", "がい", [], ["adj-i"]),
            suffix_inflection("げえ", "ごい", [], ["adj-i"]),
            suffix_inflection("せえ", "さい", [], ["adj-i"]),
            suffix_inflection("めえ", "まい", [], ["adj-i"]),
            suffix_inflection("ぜえ", "ずい", [], ["adj-i"]),
            suffix_inflection("っぜえ", "ずい", [], ["adj-i"]),
            suffix_inflection("れえ", "らい", [], ["adj-i"]),
            suffix_inflection("ちぇえ", "ちゃい", [], ["adj-i"]),
            suffix_inflection("でえ", "どい", [], ["adj-i"]),
            suffix_inflection("れえ", "れい", [], ["adj-i"]),
            suffix_inflection("べえ", "ばい", [], ["adj-i"]),
            suffix_inflection("てえ", "たい", [], ["adj-i"]),
            suffix_inflection("ねぇ", "ない", [], ["adj-i"]),
            suffix_inflection("めぇ", "むい", [], ["adj-i"]),
            suffix_inflection("みぃ", "むい", [], ["adj-i"]),
            suffix_inflection("ちぃ", "つい", [], ["adj-i"]),
            suffix_inflection("せぇ", "すい", [], ["adj-i"]),
            suffix_inflection("けぇ", "かい", [], ["adj-i"]),
            suffix_inflection("げぇ", "がい", [], ["adj-i"]),
            suffix_inflection("げぇ", "ごい", [], ["adj-i"]),
            suffix_inflection("せぇ", "さい", [], ["adj-i"]),
            suffix_inflection("めぇ", "まい", [], ["adj-i"]),
            suffix_inflection("ぜぇ", "ずい", [], ["adj-i"]),
            suffix_inflection("っぜぇ", "ずい", [], ["adj-i"]),
            suffix_inflection("れぇ", "らい", [], ["adj-i"]),
            suffix_inflection("でぇ", "どい", [], ["adj-i"]),
            suffix_inflection("れぇ", "れい", [], ["adj-i"]),
            suffix_inflection("べぇ", "ばい", [], ["adj-i"]),
            suffix_inflection("てぇ", "たい", [], ["adj-i"]),
        ],
    },
    {
        "id": "n-slang",
        "name": "n-slang",
        "rules": [
            suffix_inflection("んなさい", "りなさい", [], ["-なさい"]),
            suffix_inflection("らんない", "られない", ["adj-i"], ["adj-i"]),
            suffix_inflection("んない", "らない", ["adj-i"], ["adj-i"]),
            suffix_inflection("んなきゃ", "らなきゃ", [], ["-ゃ"]),
            suffix_inflection("んなきゃ", "れなきゃ", [], ["-ゃ"]),
        ],
    },
    {
        "id": "imperative negative slang",
        "name": "imperative negative slang",
        "rules": [
            suffix_inflection("んな", "る", [], ["v"]),
        ],
    },
    {
        "id": "kansai-ben negative",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("へん", "ない", [], ["adj-i"]),
            suffix_inflection("ひん", "ない", [], ["adj-i"]),
            suffix_inflection("せえへん", "しない", [], ["adj-i"]),
            suffix_inflection("へんかった", "なかった", ["-た"], ["-た"]),
            suffix_inflection("ひんかった", "なかった", ["-た"], ["-た"]),
            suffix_inflection("うてへん", "ってない", [], ["adj-i"]),
        ],
    },
    {
        "id": "kansai-ben -て",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("うて", "って", ["-て"], ["-て"]),
            suffix_inflection("おうて", "あって", ["-て"], ["-て"]),
            suffix_inflection("こうて", "かって", ["-て"], ["-て"]),
            suffix_inflection("ごうて", "がって", ["-て"], ["-て"]),
            suffix_inflection("そうて", "さって", ["-て"], ["-て"]),
            suffix_inflection("ぞうて", "ざって", ["-て"], ["-て"]),
            suffix_inflection("とうて", "たって", ["-て"], ["-て"]),
            suffix_inflection("どうて", "だって", ["-て"], ["-て"]),
            suffix_inflection("のうて", "なって", ["-て"], ["-て"]),
            suffix_inflection("ほうて", "はって", ["-て"], ["-て"]),
            suffix_inflection("ぼうて", "ばって", ["-て"], ["-て"]),
            suffix_inflection("もうて", "まって", ["-て"], ["-て"]),
            suffix_inflection("ろうて", "らって", ["-て"], ["-て"]),
            suffix_inflection("ようて", "やって", ["-て"], ["-て"]),
            suffix_inflection("ゆうて", "いって", ["-て"], ["-て"]),
        ],
    },
    {
        "id": "kansai-ben -た",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("うた", "った", ["-た"], ["-た"]),
            suffix_inflection("おうた", "あった", ["-た"], ["-た"]),
            suffix_inflection("こうた", "かった", ["-た"], ["-た"]),
            suffix_inflection("ごうた", "がった", ["-た"], ["-た"]),
            suffix_inflection("そうた", "さった", ["-た"], ["-た"]),
            suffix_inflection("ぞうた", "ざった", ["-た"], ["-た"]),
            suffix_inflection("とうた", "たった", ["-た"], ["-た"]),
            suffix_inflection("どうた", "だった", ["-た"], ["-た"]),
            suffix_inflection("のうた", "なった", ["-た"], ["-た"]),
            suffix_inflection("ほうた", "はった", ["-た"], ["-た"]),
            suffix_inflection("ぼうた", "ばった", ["-た"], ["-た"]),
            suffix_inflection("もうた", "まった", ["-た"], ["-た"]),
            suffix_inflection("ろうた", "らった", ["-た"], ["-た"]),
            suffix_inflection("ようた", "やった", ["-た"], ["-た"]),
            suffix_inflection("ゆうた", "いった", ["-た"], ["-た"]),
        ],
    },
    {
        "id": "kansai-ben -たら",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("うたら", "ったら", [], []),
            suffix_inflection("おうたら", "あったら", [], []),
            suffix_inflection("こうたら", "かったら", [], []),
            suffix_inflection("ごうたら", "がったら", [], []),
            suffix_inflection("そうたら", "さったら", [], []),
            suffix_inflection("ぞうたら", "ざったら", [], []),
            suffix_inflection("とうたら", "たったら", [], []),
            suffix_inflection("どうたら", "だったら", [], []),
            suffix_inflection("のうたら", "なったら", [], []),
            suffix_inflection("ほうたら", "はったら", [], []),
            suffix_inflection("ぼうたら", "ばったら", [], []),
            suffix_inflection("もうたら", "まったら", [], []),
            suffix_inflection("ろうたら", "らったら", [], []),
            suffix_inflection("ようたら", "やったら", [], []),
            suffix_inflection("ゆうたら", "いったら", [], []),
        ],
    },
    {
        "id": "kansai-ben -たり",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("うたり", "ったり", [], []),
            suffix_inflection("おうたり", "あったり", [], []),
            suffix_inflection("こうたり", "かったり", [], []),
            suffix_inflection("ごうたり", "がったり", [], []),
            suffix_inflection("そうたり", "さったり", [], []),
            suffix_inflection("ぞうたり", "ざったり", [], []),
            suffix_inflection("とうたり", "たったり", [], []),
            suffix_inflection("どうたり", "だったり", [], []),
            suffix_inflection("のうたり", "なったり", [], []),
            suffix_inflection("ほうたり", "はったり", [], []),
            suffix_inflection("ぼうたり", "ばったり", [], []),
            suffix_inflection("もうたり", "まったり", [], []),
            suffix_inflection("ろうたり", "らったり", [], []),
            suffix_inflection("ようたり", "やったり", [], []),
            suffix_inflection("ゆうたり", "いったり", [], []),
        ],
    },
    {
        "id": "kansai-ben -く",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("う", "く", [], ["-く"]),
            suffix_inflection("こう", "かく", [], ["-く"]),
            suffix_inflection("ごう", "がく", [], ["-く"]),
            suffix_inflection("そう", "さく", [], ["-く"]),
            suffix_inflection("とう", "たく", [], ["-く"]),
            suffix_inflection("のう", "なく", [], ["-く"]),
            suffix_inflection("ぼう", "ばく", [], ["-く"]),
            suffix_inflection("もう", "まく", [], ["-く"]),
            suffix_inflection("ろう", "らく", [], ["-く"]),
            suffix_inflection("よう", "よく", [], ["-く"]),
            suffix_inflection("しゅう", "しく", [], ["-く"]),
        ],
    },
    {
        "id": "kansai-ben adjective -て",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("うて", "くて", ["-て"], ["-て"]),
            suffix_inflection("こうて", "かくて", ["-て"], ["-て"]),
            suffix_inflection("ごうて", "がくて", ["-て"], ["-て"]),
            suffix_inflection("そうて", "さくて", ["-て"], ["-て"]),
            suffix_inflection("とうて", "たくて", ["-て"], ["-て"]),
            suffix_inflection("のうて", "なくて", ["-て"], ["-て"]),
            suffix_inflection("ぼうて", "ばくて", ["-て"], ["-て"]),
            suffix_inflection("もうて", "まくて", ["-て"], ["-て"]),
            suffix_inflection("ろうて", "らくて", ["-て"], ["-て"]),
            suffix_inflection("ようて", "よくて", ["-て"], ["-て"]),
            suffix_inflection("しゅうて", "しくて", ["-て"], ["-て"]),
        ],
    },
    {
        "id": "kansai-ben adjective negative",
        "name": "kansai-ben",
        "rules": [
            suffix_inflection("うない", "くない", ["adj-i"], ["adj-i"]),
            suffix_inflection("こうない", "かくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("ごうない", "がくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("そうない", "さくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("とうない", "たくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("のうない", "なくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("ぼうない", "ばくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("もうない", "まくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("ろうない", "らくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("ようない", "よくない", ["adj-i"], ["adj-i"]),
            suffix_inflection("しゅうない", "しくない", ["adj-i"], ["adj-i"]),
        ],
    },
]
