package:
  name: pydantic_core
  version: "2.46.5"

build:
  number: 0

source:
  path: ../../sources/pydantic-core

requirements:
  build:
    - rust
    - maturin 1.15.0
  host:
    - python

about:
  license_file: LICENSE
