"""Command-line entry point for the AnkiDroid API sync."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .core import MANIFEST_PATH, PINNED_UPSTREAM, SyncError, check, check_upstream, refresh


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="sync the pinned AnkiDroid API source surface")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[3],
        help=argparse.SUPPRESS,
    )
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument(
        "--check",
        action="store_true",
        help="verify generated bytes against the committed manifest (offline)",
    )
    actions.add_argument(
        "--refresh",
        action="store_true",
        help="regenerate from the exact, clean pinned checkout",
    )
    actions.add_argument(
        "--check-upstream",
        action="store_true",
        help="prove byte equality against the exact, clean pinned checkout",
    )
    parser.add_argument(
        "--source",
        type=Path,
        help="root of an AnkiDroid git checkout (required for refresh/upstream proof)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    if args.check and args.source is not None:
        parser.error("--check is manifest-only and does not accept --source; use --check-upstream")
    if not args.check and args.source is None:
        parser.error("--source is required with --refresh and --check-upstream")

    try:
        if args.check:
            check(args.repo_root)
            print(f"AnkiDroid API manifest check OK: {MANIFEST_PATH}")
        elif args.refresh:
            refresh(args.repo_root, args.source)
            print("AnkiDroid API refreshed from verified " f"{PINNED_UPSTREAM.tag} @ {PINNED_UPSTREAM.commit}")
        else:
            check_upstream(args.repo_root, args.source)
            print(
                "AnkiDroid API verified-upstream byte equality OK: " f"{PINNED_UPSTREAM.tag} @ {PINNED_UPSTREAM.commit}"
            )
    except SyncError as exc:
        print(f"AnkiDroid API sync failed: {exc}", file=sys.stderr)
        return 1
    return 0
