"""Data pack manifest for fa: the hazm wheel's ``data/`` directory, and nothing else.

Hand-pinned, not generated by ``scripts/pin_language_pack.py``: that script
resolves a pip dependency closure, and Persian needs no package on
``sys.path`` at all. The analyser itself is the in-tree port under
``languages/fa/_hazm/`` (MIT, ``licenses/hazm/``); only the lexical tables are
too large to commit, so the pack carries those five ``.dat`` files and the
wheel's ``hazm/`` package is never extracted.

Extracting the code would not work anyway: hazm 0.12.1 declares
``Requires-Python >=3.12,<3.14``, uses PEP 695 syntax (a SyntaxError on CI's
3.11 leg) and imports nltk/flashtext/tqdm from its ``__init__``.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

#: Not an importable module: ``find_spec`` can never answer for it, which is
#: what stops the installer calling the pack satisfied by something pip put on
#: ``sys.path``. ``availability.FA_DATA_COMPONENT`` is the same string.
_HAZM_DATA = PackComponent(
    import_name="hazm_data",
    required=True,
    # Every table PersianLexicon loads. A half-extracted pack is reported
    # missing rather than parsing Persian with three of five tables.
    sentinels=("words.dat", "verbs.dat", "iverbs.dat", "iwords.dat", "stopwords.dat"),
    universal=ArtifactSpec(
        # hazm-0.12.1-py3-none-any.whl, 887,193 B
        url=(
            "https://files.pythonhosted.org/packages/14/85/"
            "02f95ca414a5d629239a3fde8f4134a2355dd023044219192e48562dee71/"
            "hazm-0.12.1-py3-none-any.whl"
        ),
        sha256="91507896f5b77dcfe26c710b457801e1204ab0d86dcb756a7ab5912719108db0",
        kind="wheel",
        # Data only: the sibling ``hazm/`` modules stay in the wheel.
        member_prefix="hazm/data/",
    ),
)

PACK = LanguagePack(
    code="fa",
    # The wheel is 0.87 MB on the wire; the extracted tables are 3.3 MB.
    approx_download_mb=1,
    components=(_HAZM_DATA,),
    requires=(),
)

__all__ = ["PACK"]
