"""Dependency-pack manifest for ro, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/ro.resolved.json with it.

Android overlay (decision 2: code ships in the APK, only data is downloaded). The
upstream manifest, except that every data component excludes its Python members
and each code sentinel is replaced by the data file Android reads in its place:
a spaCy model's ``__init__.py`` by the ``meta.json`` that
``spacy.util.load_model_from_init_py`` opens, a pymorphy3 dictionary package's
``__init__.py`` by ``data/meta.json``. The dictionaries' ``.dist-info`` root
members (pymorphy3's entry-point discovery) are dropped: Android passes the
dictionary path itself. Rebase on any upstream change.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="ro_core_news_sm",
        required=True,
        sentinels=("meta.json", "ro_core_news_sm-3.8.0/config.cfg", "ro_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # ro_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/ro_core_news_sm-3.8.0/ro_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="3cebfba2437131efe95345adcc7ea2131e4463915652df9099c577e618460cd9",
            kind="wheel",
            member_prefix="ro_core_news_sm/",
            exclude=("__init__.py",),
        ),
    ),
)

PACK = LanguagePack(
    code="ro",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
