"""Dependency-pack manifest for tr, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/tr.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="cloudpickle",
        required=True,
        sentinels=("__init__.py",),
        universal=ArtifactSpec(
            # cloudpickle-3.1.2-py3-none-any.whl
            url="https://files.pythonhosted.org/packages/88/39/799be3f2f0f38cc727ee3b4f1445fe6d5e4133064ec2e4115069418a5bb6/cloudpickle-3.1.2-py3-none-any.whl",
            sha256="9acb47f6afd73f60dc1df93bb801b472f05ff42fa6c84167d25cb206be1fbf4a",
            kind="wheel",
            member_prefix="cloudpickle/",
        ),
    ),
    PackComponent(
        import_name="colorama",
        required=True,
        sentinels=("__init__.py",),
        universal=ArtifactSpec(
            # colorama-0.4.6-py2.py3-none-any.whl
            url="https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl",
            sha256="4f1d9991f5acc0ca119f9d443620b77f9d6b33703e51011c16baf57afb285fc6",
            kind="wheel",
            member_prefix="colorama/",
        ),
    ),
    PackComponent(
        import_name="defusedxml",
        required=True,
        sentinels=("__init__.py",),
        universal=ArtifactSpec(
            # defusedxml-0.7.1-py2.py3-none-any.whl
            url="https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl",
            sha256="a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61",
            kind="wheel",
            member_prefix="defusedxml/",
        ),
    ),
    PackComponent(
        import_name="joblib",
        required=True,
        sentinels=("__init__.py",),
        universal=ArtifactSpec(
            # joblib-1.6.0-py3-none-any.whl
            url="https://files.pythonhosted.org/packages/18/53/84099323c2ec4be98d935f63c033ac4151ee83836ca1050ede3b3aadf155/joblib-1.6.0-py3-none-any.whl",
            sha256="3dbbf9f6e4b592a2357b854608e980fe6390d131d7a82f011a377ef2ebef7aba",
            kind="wheel",
            member_prefix="joblib/",
        ),
    ),
    PackComponent(
        import_name="nltk",
        required=True,
        sentinels=("__init__.py",),
        universal=ArtifactSpec(
            # nltk-3.10.3-py3-none-any.whl
            url="https://files.pythonhosted.org/packages/b6/6d/ebd2af4640b12168fdf0cb74b6118df2f32a2f62ec7e0c06fbfd80706639/nltk-3.10.3-py3-none-any.whl",
            sha256="ff9598a8e20518ee0d557745890cc4435b9578489e2dcbc69c4f81fa060caf7c",
            kind="wheel",
            member_prefix="nltk/",
        ),
    ),
    PackComponent(
        import_name="regex",
        required=True,
        sentinels=("__init__.py",),
        abi=(3, 12),
        per_platform={
            ("darwin", "arm64"): ArtifactSpec(
                # regex-2026.9.10-cp312-cp312-macosx_10_13_universal2.whl
                url="https://files.pythonhosted.org/packages/32/c8/bfbe893e90ee0148bd2860dd086f09b5d2080ca2b125f740c2e118c16982/regex-2026.9.10-cp312-cp312-macosx_10_13_universal2.whl",
                sha256="880ac684c27176464c00c3fdc456116364f5ebc70da07aad0c2d4a7ba45e98db",
                kind="wheel",
                member_prefix="regex/",
            ),
            ("darwin", "x86_64"): ArtifactSpec(
                # regex-2026.9.10-cp312-cp312-macosx_10_13_universal2.whl
                url="https://files.pythonhosted.org/packages/32/c8/bfbe893e90ee0148bd2860dd086f09b5d2080ca2b125f740c2e118c16982/regex-2026.9.10-cp312-cp312-macosx_10_13_universal2.whl",
                sha256="880ac684c27176464c00c3fdc456116364f5ebc70da07aad0c2d4a7ba45e98db",
                kind="wheel",
                member_prefix="regex/",
            ),
            ("linux", "aarch64"): ArtifactSpec(
                # regex-2026.9.10-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl
                url="https://files.pythonhosted.org/packages/89/51/3fb5fe0d32f4cf0bc982286722c729a8d6f522d2fa2d5d14a702d9fc87f8/regex-2026.9.10-cp312-cp312-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl",
                sha256="4c66d54042a14a503907d81861b8a5235e6d1f03d4fbc1d8767f652eaf957ac1",
                kind="wheel",
                member_prefix="regex/",
            ),
            ("linux", "x86_64"): ArtifactSpec(
                # regex-2026.9.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
                url="https://files.pythonhosted.org/packages/cb/f5/dcdf5e0d898024005cfcce631e3e934d111dfbe177ca0b7f253ae8a735a2/regex-2026.9.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl",
                sha256="2e67f8843f0e4b931f1fa860bf3bbe4134b714c0155cc5c7c0d7ea450230aae0",
                kind="wheel",
                member_prefix="regex/",
            ),
            ("win32", "AMD64"): ArtifactSpec(
                # regex-2026.9.10-cp312-cp312-win_amd64.whl
                url="https://files.pythonhosted.org/packages/ad/d4/4dcd0a05d3e97ca829165df1c39717f899d1d484dac8a6032439f2cb8d6d/regex-2026.9.10-cp312-cp312-win_amd64.whl",
                sha256="4db7d00c4afbfbb55b8e17b1e371da11418ea9389b030acec63c1fa4c7ad4b86",
                kind="wheel",
                member_prefix="regex/",
            ),
        },
    ),
    PackComponent(
        import_name="zeyrek",
        required=True,
        sentinels=("__init__.py",),
        universal=ArtifactSpec(
            # zeyrek-0.1.3-py2.py3-none-any.whl
            url="https://files.pythonhosted.org/packages/7f/5b/76970fab035d2e2649ba06af037c394b9690d0e07a8faf53817ccccb3951/zeyrek-0.1.3-py2.py3-none-any.whl",
            sha256="23649bb49322a52d1e94959029b047fa4037bc540762819feb1096aa976b25b5",
            kind="wheel",
            member_prefix="zeyrek/",
        ),
    ),
)

PACK = LanguagePack(
    code="tr",
    approx_download_mb=4,
    components=COMPONENTS,
    requires=(),
)

__all__ = ["PACK"]
