package com.ichi2.anki.api

/** Release AnkiDroid endpoint values formerly generated by its API library module. */
internal object BuildConfig {
    const val AUTHORITY = "com.ichi2.anki.flashcards"
    const val READ_WRITE_PERMISSION = "com.ichi2.anki.permission.READ_WRITE_DATABASE"
}
