package:
  name: chaquopy-libmecab
  version: "0.996"

source:
  path: ../../sources/mecab

build:
  number: 0

requirements:
  build: []
  host: []

about:
  license: BSD-3-Clause
  license_file: COPYING
