package:
  name: rustling
  version: "0.9.0"

build:
  number: 0

source:
  path: ../../sources/rustling

requirements:
  build:
    - rust
    - maturin 1.15.0
  host:
    - python

about:
  license_file: LICENSE.md
