from __future__ import annotations

import sys
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

TOOL_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = TOOL_ROOT.parents[1]
sys.path.insert(0, str(TOOL_ROOT))

from ankidroid_api_sync.core import GENERATED_SOURCE_ROOT, VENDORED_FILES  # noqa: E402


class RepositoryLayoutTest(unittest.TestCase):
    def test_app_manifest_declares_release_ankidroid_access(self) -> None:
        android_namespace = "http://schemas.android.com/apk/res/android"
        name_attribute = f"{{{android_namespace}}}name"
        manifest = ET.parse(REPO_ROOT / "app/src/main/AndroidManifest.xml").getroot()

        permissions = {
            element.attrib[name_attribute]
            for element in manifest.findall("uses-permission")
            if name_attribute in element.attrib
        }
        queried_packages = {
            element.attrib[name_attribute]
            for element in manifest.findall("queries/package")
            if name_attribute in element.attrib
        }

        self.assertIn("com.ichi2.anki.permission.READ_WRITE_DATABASE", permissions)
        self.assertIn("com.ichi2.anki", queried_packages)

    def test_generated_tree_contains_only_the_seven_pinned_api_sources(self) -> None:
        generated_root = REPO_ROOT / GENERATED_SOURCE_ROOT
        actual = {
            path.relative_to(REPO_ROOT).as_posix()
            for path in generated_root.rglob("*.kt")
            if path.is_file()
        }
        expected = {
            entry.destination_path.as_posix()
            for entry in VENDORED_FILES
            if entry.kind == "kotlin-source"
        }

        self.assertEqual(7, len(expected))
        self.assertEqual(expected, actual)
        self.assertFalse(any(path.endswith("BuildConfig.kt") for path in actual))

    def test_hand_owned_build_config_shim_has_only_release_constants(self) -> None:
        shim = (
            REPO_ROOT
            / "app/src/main/kotlin/com/ichi2/anki/api/BuildConfig.kt"
        ).read_text(encoding="utf-8")
        self.assertEqual(
            """package com.ichi2.anki.api

/** Release AnkiDroid endpoint values formerly generated by its API library module. */
internal object BuildConfig {
    const val AUTHORITY = "com.ichi2.anki.flashcards"
    const val READ_WRITE_PERMISSION = "com.ichi2.anki.permission.READ_WRITE_DATABASE"
}
""",
            shim,
        )

    def test_single_app_module_compiles_the_separate_generated_root(self) -> None:
        settings = (REPO_ROOT / "settings.gradle.kts").read_text(encoding="utf-8")
        app_gradle = (REPO_ROOT / "app/build.gradle.kts").read_text(encoding="utf-8")

        self.assertIn('include(":app")', settings)
        self.assertNotRegex(settings, r'include\([^)]*ankidroid')
        self.assertIn(
            'getByName("main").java.srcDir("src/main/ankidroidApi/kotlin")',
            app_gradle,
        )

    def test_lint_excludes_only_the_generated_api_boundary_globally(self) -> None:
        lint = ET.parse(REPO_ROOT / "app/lint.xml").getroot()
        issues = lint.findall("issue")
        expected_path = GENERATED_SOURCE_ROOT.relative_to("app").as_posix() + "/"

        self.assertEqual("lint", lint.tag)
        self.assertEqual({}, lint.attrib)
        self.assertEqual(1, len(issues))
        self.assertEqual({"id": "all"}, issues[0].attrib)
        self.assertEqual(
            [{"path": expected_path}],
            [ignore.attrib for ignore in issues[0].findall("ignore")],
        )
        self.assertEqual(1, len(issues[0]))
        self.assertEqual(
            REPO_ROOT / GENERATED_SOURCE_ROOT,
            REPO_ROOT / "app" / expected_path,
        )


if __name__ == "__main__":
    unittest.main()
