from __future__ import annotations

import sys
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

TOOL_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = TOOL_ROOT.parents[1]
sys.path.insert(0, str(TOOL_ROOT))

from ankidroid_api_sync.core import GENERATED_SOURCE_ROOT, VENDORED_FILES  # noqa: E402


class RepositoryLayoutTest(unittest.TestCase):
    def test_app_manifest_declares_release_ankidroid_access(self) -> None:
        android_namespace = "http://schemas.android.com/apk/res/android"
        name_attribute = f"{{{android_namespace}}}name"
        manifest = ET.parse(REPO_ROOT / "app/src/main/AndroidManifest.xml").getroot()

        permissions = {
            element.attrib[name_attribute]
            for element in manifest.findall("uses-permission")
            if name_attribute in element.attrib
        }
        queried_packages = {
            element.attrib[name_attribute]
            for element in manifest.findall("queries/package")
            if name_attribute in element.attrib
        }

        self.assertIn("com.ichi2.anki.permission.READ_WRITE_DATABASE", permissions)
        self.assertIn("com.ichi2.anki", queried_packages)

    def test_generated_tree_contains_only_the_seven_pinned_api_sources(self) -> None:
        generated_root = REPO_ROOT / GENERATED_SOURCE_ROOT
        actual = {path.relative_to(REPO_ROOT).as_posix() for path in generated_root.rglob("*.kt") if path.is_file()}
        expected = {entry.destination_path.as_posix() for entry in VENDORED_FILES if entry.kind == "kotlin-source"}

        self.assertEqual(7, len(expected))
        self.assertEqual(expected, actual)
        self.assertFalse(any(path.endswith("BuildConfig.kt") for path in actual))

    def test_hand_owned_build_config_shim_has_only_release_constants(self) -> None:
        shim = (REPO_ROOT / "app/src/main/kotlin/com/ichi2/anki/api/BuildConfig.kt").read_text(encoding="utf-8")
        self.assertEqual(
            """package com.ichi2.anki.api

/** Release AnkiDroid endpoint values formerly generated by its API library module. */
internal object BuildConfig {
    const val AUTHORITY = "com.ichi2.anki.flashcards"
    const val READ_WRITE_PERMISSION = "com.ichi2.anki.permission.READ_WRITE_DATABASE"
}
""",
            shim,
        )

    def test_single_app_module_compiles_the_separate_generated_root(self) -> None:
        settings = (REPO_ROOT / "settings.gradle.kts").read_text(encoding="utf-8")
        app_gradle = (REPO_ROOT / "app/build.gradle.kts").read_text(encoding="utf-8")

        self.assertIn('include(":app")', settings)
        self.assertNotRegex(settings, r"include\([^)]*ankidroid")
        self.assertIn(
            'getByName("main").java.srcDir("src/main/ankidroidApi/kotlin")',
            app_gradle,
        )

    def test_lint_config_carries_only_sanctioned_global_issues(self) -> None:
        """Pin the sanctioned set by id, not a count: any other global override is a gate hole.

        Two entries are sanctioned. The generated-API boundary exclusion keeps every check off the
        byte-pinned upstream snapshot. MissingTranslation drops to informational for the reason
        tools/localization/audit_android_localizations.py reports it as an advisory: a key absent
        from values-xx resolves to values/ at runtime, so translation completeness is a backlog.
        ExtraTranslation and StringFormatInvalid stay errors.
        """
        lint = ET.parse(REPO_ROOT / "app/lint.xml").getroot()
        declared = lint.findall("issue")
        issues = {element.attrib.get("id"): element for element in declared}
        expected_path = GENERATED_SOURCE_ROOT.relative_to("app").as_posix() + "/"

        self.assertEqual("lint", lint.tag)
        self.assertEqual({}, lint.attrib)
        self.assertEqual({"all", "MissingTranslation"}, set(issues))
        # Two elements sharing an id would collapse into one key above.
        self.assertEqual(len(issues), len(declared))

        boundary = issues["all"]
        self.assertEqual({"id": "all"}, boundary.attrib)
        self.assertEqual(
            [{"path": expected_path}],
            [ignore.attrib for ignore in boundary.findall("ignore")],
        )
        self.assertEqual(1, len(boundary))
        self.assertEqual(
            REPO_ROOT / GENERATED_SOURCE_ROOT,
            REPO_ROOT / "app" / expected_path,
        )

        untranslated = issues["MissingTranslation"]
        self.assertEqual(
            {"id": "MissingTranslation", "severity": "informational"},
            untranslated.attrib,
        )
        self.assertEqual(0, len(untranslated))


if __name__ == "__main__":
    unittest.main()
