"""The shared spaCy engine pack (``languages.SHARED_PACK_CODES``, R2).

Not a mining language: never in ``AVAILABLE_LANGUAGES``, never discovered as a
profile. ``pack.py`` is GENERATED by ``scripts/pin_language_pack.py runtime``
(spaCy + its native closure, cp312 per release platform, minus everything
``requirements.lock`` pins); every spaCy model pack ``requires`` it.
"""
