#!/usr/bin/env python3
"""Generate the checked-in Kotlin table for vendored desktop theme palettes."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PALETTES_DIRECTORY = REPO_ROOT / "tools/themes/palettes"
GENERATED_KOTLIN_PATH = REPO_ROOT / "app/src/main/kotlin/com/ankiminer/android/ui/theme/generated/ThemePalettes.kt"
HEX_COLOR = re.compile(r"#[0-9a-fA-F]{6}")


class ThemePaletteError(ValueError):
    """The vendored desktop theme data cannot be rendered safely."""


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="generate Kotlin theme palettes from vendored desktop JSON")
    parser.add_argument(
        "--check",
        action="store_true",
        help="detect generated Kotlin drift without writing",
    )
    return parser


def _kotlin_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def _pascal_case_key(key: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^0-9A-Za-z]+", key) if part)


def _required_string(data: dict[str, object], field: str, path: Path) -> str:
    value = data.get(field)
    if not isinstance(value, str) or not value.strip():
        raise ThemePaletteError(f"{path.name}: {field} must be a non-empty string")
    return value


def _optional_string(data: dict[str, object], field: str, path: Path) -> str | None:
    value = data.get(field)
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise ThemePaletteError(f"{path.name}: {field} must be a non-empty string when present")
    return value


def _load_palette(path: Path) -> dict[str, object]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ThemePaletteError(f"{path.name}: cannot read JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ThemePaletteError(f"{path.name}: theme must be a JSON object")

    colors = data.get("colors")
    if not isinstance(colors, dict) or len(colors) != 46:
        raise ThemePaletteError(f"{path.name}: colors must be an object with exactly 46 entries")
    validated_colors: dict[str, str] = {}
    for slot, color in colors.items():
        if not isinstance(slot, str) or not isinstance(color, str) or not HEX_COLOR.fullmatch(color):
            raise ThemePaletteError(f"{path.name}: colors must map slots to #rrggbb strings")
        validated_colors[slot] = color

    return {
        "key": path.stem,
        "display_name": _required_string(data, "name", path),
        "family": _optional_string(data, "family", path),
        "variant": _optional_string(data, "variant", path),
        "colors": validated_colors,
    }


def _kotlin_nullable_string(value: str | None) -> str:
    return "null" if value is None else f'"{_kotlin_string(value)}"'


def generate_kotlin() -> bytes:
    paths = sorted(PALETTES_DIRECTORY.glob("*.json"))
    if not paths:
        raise ThemePaletteError(f"no palettes found in {PALETTES_DIRECTORY.relative_to(REPO_ROOT)}")
    palettes = [_load_palette(path) for path in paths]

    lines = [
        "// Generated by tools/themes/generate_theme_palettes.py; do not edit.",
        "// Source palettes: tools/themes/palettes/.",
        "",
        "package com.ankiminer.android.ui.theme.generated",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import com.ankiminer.android.ui.theme.ThemePalette",
        "",
    ]
    palette_names: list[str] = []
    for palette in palettes:
        key = palette["key"]
        display_name = palette["display_name"]
        family = palette["family"]
        variant = palette["variant"]
        colors = palette["colors"]
        if not isinstance(key, str) or not isinstance(display_name, str) or not isinstance(colors, dict):
            raise AssertionError("validated palette has an unexpected type")
        if family is not None and not isinstance(family, str):
            raise AssertionError("validated palette family has an unexpected type")
        if variant is not None and not isinstance(variant, str):
            raise AssertionError("validated palette variant has an unexpected type")

        variable_name = _pascal_case_key(key)
        palette_names.append(variable_name)
        lines.extend(
            (
                f"private val {variable_name}: ThemePalette =",
                "    ThemePalette(",
                f'        key = "{_kotlin_string(key)}",',
                f'        displayName = "{_kotlin_string(display_name)}",',
                f"        family = {_kotlin_nullable_string(family)},",
                f"        variant = {_kotlin_nullable_string(variant)},",
                "        colors = mapOf(",
            )
        )
        for slot in sorted(colors):
            color = colors[slot]
            if not isinstance(slot, str) or not isinstance(color, str):
                raise AssertionError("validated color has an unexpected type")
            lines.append(f'            "{_kotlin_string(slot)}" to Color(0xFF{color[1:].upper()}),')
        lines.extend(
            (
                "        ),",
                "    )",
                "",
            )
        )

    lines.extend(
        (
            "internal object GeneratedThemePalettes {",
            "    val all: List<ThemePalette> =",
            "        listOf(",
            *(f"            {name}," for name in palette_names),
            "        )",
            "}",
        )
    )
    return ("\n".join(lines) + "\n").encode("utf-8")


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        generated = generate_kotlin()
        if args.check:
            try:
                current = GENERATED_KOTLIN_PATH.read_bytes()
            except OSError:
                current = None
            if current != generated:
                print(
                    "Theme palettes Kotlin is stale; run tools/themes/generate_theme_palettes.py",
                    file=sys.stderr,
                )
                return 1
            print(f"Theme palettes Kotlin check OK: {GENERATED_KOTLIN_PATH.relative_to(REPO_ROOT)}")
        else:
            GENERATED_KOTLIN_PATH.parent.mkdir(parents=True, exist_ok=True)
            GENERATED_KOTLIN_PATH.write_bytes(generated)
            print(f"Theme palettes Kotlin generated: {GENERATED_KOTLIN_PATH.relative_to(REPO_ROOT)}")
    except ThemePaletteError as exc:
        print(f"Theme palette generation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
