package:
  name: spacy
  version: "3.8.14"

build:
  number: 0
  script_env:
    - SPACY_NUM_BUILD_JOBS=16

source:
  path: ../../sources/spacy

requirements:
  build:
    - cython 3.2.4
  host:
    - python

about:
  license_file: LICENSE
